### ISSUE TITLE
Updated analysis: molecular subtyping HGG missed TP53 for sample with alteration

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/OpenPBTA-analysis#407]
#### What analysis module should be updated and why?
https://pedcbioportal.kidsfirstdrc.org/patient/clinicalData?studyId=pbta_all&caseId=PT_Z4PJA6KT

molecular subtyping HGG - `BS_853PNV7P` `7316-1763_Derived Cell Line_Serum-based_3` has a TP53 alteration present in results tables, but was not annotated as such for molecular subtype. Could this be due to a low TP53 classifier score? The presence of the hotspot mutation should not depend on the classifier score.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Check the code to determine why this was missed and update.

**Comment by zzgeng** [comment]
The issue is raised from `tp53_altered_status.tsv` file from `tp53_nf1_score` module, where `tp53_altered` of BS_853PNV7P is shown as "other". In 10-HGG-TP53 script, only samples with "activated" or "loss" in `tp53_altered` would have TP53 in molecular subtype (https://github.com/d3b-center/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-HGG/10-HGG-TP53-annotation.Rmd#L57C3-L60C9).

**Comment by zzgeng** [comment]
Following the previous comment, I took a look at `tp53_nf1_score` module. In `tp53_nf1_score/05-tp53-altered-annotation.Rmd`, BS_853PNV7P has a low tp53-score of 0.4722809, which leads to the tp53-altered shows as `other`.

**Comment by jharenza** [comment]
updated in #474
